/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GymsRouteImport } from './routes/gyms'
import { Route as LeadFollowUpAutomationRouteImport } from './routes/lead-follow-up-automation'
import { Route as LeisureRouteImport } from './routes/leisure'
import { Route as PilatesYogaStudiosRouteImport } from './routes/pilates-yoga-studios'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PtRouteImport } from './routes/pt'
import { Route as RapidServicesRouteImport } from './routes/rapid-services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GymsRoute = GymsRouteImport.update({
  id: '/gyms',
  path: '/gyms',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadFollowUpAutomationRoute = LeadFollowUpAutomationRouteImport.update({
  id: '/lead-follow-up-automation',
  path: '/lead-follow-up-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const LeisureRoute = LeisureRouteImport.update({
  id: '/leisure',
  path: '/leisure',
  getParentRoute: () => rootRouteImport,
} as any)
const PilatesYogaStudiosRoute = PilatesYogaStudiosRouteImport.update({
  id: '/pilates-yoga-studios',
  path: '/pilates-yoga-studios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidServicesRoute = RapidServicesRouteImport.update({
  id: '/rapid-services',
  path: '/rapid-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gyms': typeof GymsRoute
  '/lead-follow-up-automation': typeof LeadFollowUpAutomationRoute
  '/leisure': typeof LeisureRoute
  '/pilates-yoga-studios': typeof PilatesYogaStudiosRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/pt': typeof PtRoute
  '/rapid-services': typeof RapidServicesRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gyms': typeof GymsRoute
  '/lead-follow-up-automation': typeof LeadFollowUpAutomationRoute
  '/leisure': typeof LeisureRoute
  '/pilates-yoga-studios': typeof PilatesYogaStudiosRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/pt': typeof PtRoute
  '/rapid-services': typeof RapidServicesRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gyms': typeof GymsRoute
  '/lead-follow-up-automation': typeof LeadFollowUpAutomationRoute
  '/leisure': typeof LeisureRoute
  '/pilates-yoga-studios': typeof PilatesYogaStudiosRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/pt': typeof PtRoute
  '/rapid-services': typeof RapidServicesRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/gyms'
    | '/lead-follow-up-automation'
    | '/leisure'
    | '/pilates-yoga-studios'
    | '/privacy'
    | '/process'
    | '/pt'
    | '/rapid-services'
    | '/solutions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/gyms'
    | '/lead-follow-up-automation'
    | '/leisure'
    | '/pilates-yoga-studios'
    | '/privacy'
    | '/process'
    | '/pt'
    | '/rapid-services'
    | '/solutions'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/gyms'
    | '/lead-follow-up-automation'
    | '/leisure'
    | '/pilates-yoga-studios'
    | '/privacy'
    | '/process'
    | '/pt'
    | '/rapid-services'
    | '/solutions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GymsRoute: typeof GymsRoute
  LeadFollowUpAutomationRoute: typeof LeadFollowUpAutomationRoute
  LeisureRoute: typeof LeisureRoute
  PilatesYogaStudiosRoute: typeof PilatesYogaStudiosRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  PtRoute: typeof PtRoute
  RapidServicesRoute: typeof RapidServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyms': {
      id: '/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof GymsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-follow-up-automation': {
      id: '/lead-follow-up-automation'
      path: '/lead-follow-up-automation'
      fullPath: '/lead-follow-up-automation'
      preLoaderRoute: typeof LeadFollowUpAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leisure': {
      id: '/leisure'
      path: '/leisure'
      fullPath: '/leisure'
      preLoaderRoute: typeof LeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilates-yoga-studios': {
      id: '/pilates-yoga-studios'
      path: '/pilates-yoga-studios'
      fullPath: '/pilates-yoga-studios'
      preLoaderRoute: typeof PilatesYogaStudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapid-services': {
      id: '/rapid-services'
      path: '/rapid-services'
      fullPath: '/rapid-services'
      preLoaderRoute: typeof RapidServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GymsRoute: GymsRoute,
  LeadFollowUpAutomationRoute: LeadFollowUpAutomationRoute,
  LeisureRoute: LeisureRoute,
  PilatesYogaStudiosRoute: PilatesYogaStudiosRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  PtRoute: PtRoute,
  RapidServicesRoute: RapidServicesRoute,
  SolutionsRoute: SolutionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
